### ISSUE TITLE
Deep undertanding

### ISSUE THREAD

**Issue by gissemari** [MorvanZhou/tutorials#19]
Hi, 
Can you recommend any source to try to understand the real architecture done with tensorflow in the classification of RNN (MNIST). I thought that the simplest RNN would work with 3 Weight matrixes. W_hx, W_hh and W_yh but I just saw two in the tutorial and I don't understand very well why.

Regards,
Gissella B.

**Comment by MorvanZhou** [comment]
Hi Gisselle,

Your understanding is right, there are three Weight matrixes all the time.
The weights['in'] you have seen in the example is W_hx, weights['out'] is
W_yh. The third one W_hh is in the cell, we just need to define the hidden
units size for the cell instead of defining W_hh.

Hope this would help you.

Regards,
Morvan

**Comment by gissemari** [comment]
Oh, I see..thanks for the explanation! 
So BasicLSTMCell() would create a hidden recurrent layer which would create the W_hh matrix? One more question. I have a testSet of different size of a batch size... is there a way to change the batchsize we used here: lstm_cell.zero_state(batch_size, dtype=tf.float32)?

Regards,
Gissella B.

**Comment by MorvanZhou** [comment]
BasicLSTMCell() would create a hidden recurrent layer which would create
the W_hh matrix?

Answer: Yes, it will.

I have a testSet of different size of a batch size... is there a way to
change the batchsize we used here: lstm_cell.zero_state(batch_size,
dtype=tf.float32)?

Answer: I also faced this issue (my issue is the different time_steps in
training and testing), and my solution is to create a test-RNN with new
parameters and restore the Weights and biases from a saved Train-RNN. I
don't think this is a good solution but I don't see other better answers.

**Comment by gissemari** [comment]
Thank you. I managed to fixed the time_steps of all my instances and I am doing cross validation so I can have equal-size training batchs and test batch. I'm still looking for an example to manage different time_steps, there should be a more formal solution than the one you mention right? What if instances in the same training set has different time_steps?

**Comment by MorvanZhou** [comment]
I figured out a new method to deal with the different time steps by using variable_scope: https://github.com/MorvanZhou/tutorials/blob/master/tensorflowTUT/tf22_scope/tf22_RNN_scope.py
