### ISSUE TITLE
周大神有一个问题想请教你

### ISSUE THREAD

**Issue by bournes** [MorvanZhou/tutorials#2]
我是你的粉丝
一个中国的TENSORFLOW爱好者
我很想做一个属于自己的AI聊天机器人，但是苦于nltk就没有中文的，所以很想知道如果我想做一个中文的聊天机器人该从何下手。我的代码原型是https://github.com/Conchylicultor/DeepQA 这个。研究了很久，但是 就是搞不定中文。。望你有空的时候看看。。我期待能搞出一个中文的。。

PS : 中文学习语料库我可以自己码出来，现在DEEPQA是用的英文的语料库，我觉得问题的重点可能是在如何中文分词，好像GITHUB上有一个JIEBA分词的东西，但是真不知道如何使用。

期待你的答复 !!!!

**Comment by MorvanZhou** [comment]
你好,
我可能帮不上什么忙, 因为自己没有往语言方面研究. 不过我创建的 qq 群里好像有人研究语言方面的, 我记得有人也问过分词的东西. 你可以在 qq
群上问问. 看有没有其他高手能解答. 531670665

谢谢.

2016-10-09 0:34 GMT+11:00 bournes <notifications@github.com>:

**Comment by bournes** [comment]
谢谢！
