### ISSUE TITLE
can not get the graph 

### ISSUE THREAD

**Issue by WoNiuHu** [MorvanZhou/tutorials#20]
hi , I used your code , and run in the terminal , but i can not get the graph as your video shows , can you explain and try again whether the code has left some sentence . thanks

**Comment by MorvanZhou** [comment]
In many cases, this issue is caused by using other browsers rather than
Google Chrome. My advice is to run your tensorboard and put the link in
Chrome. Let me know if this suggestion cannot solve your problem.

**Comment by WoNiuHu** [comment]
Hi , Morvan
    Thanks for your reply, I just put the link in Chrome , but it still does not work. 


Best regards
Haibing





At 2016-11-06 15:29:44, "Morvan" <notifications@github.com> wrote:
In many cases, this issue is caused by using other browsers rather than
Google Chrome. My advice is to run your tensorboard and put the link in
Chrome. Let me know if this suggestion cannot solve your problem.

**Comment by WoNiuHu** [comment]
Hi ,Morvan
   I used  pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0rc0-py2-none-any.whl 
to install tensorflow , maybe it's the newest  , if not , how to update it ,for there are little webpages of this . maybe you can give me an command how to update , thanks 


Best regards
 Haibing





At 2016-11-06 16:58:04, "Morvan" <notifications@github.com> wrote:
Hi Haibing,

Please try upgrade you tensorflow as well if you haven't. Please tell me
more details regarding to you case if that doesn't work.

Regards,

Morvan

**Comment by MorvanZhou** [comment]
Hi,
Please follow these steps again like the first time you install tf.
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html
It will install the latest version.

Regards,

**Comment by WoNiuHu** [comment]
Thanks, i have update the tensorflow ,  
when i run the command
 in terminal , it has an error , and still haven't the graph 

--

At 2016-11-06 17:20:25, "Morvan" <notifications@github.com> wrote:
Hi,
Please follow these steps again like the first time you install tf.
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html
It will install the latest version.

Regards,

**Comment by MorvanZhou** [comment]
What was the error info?

**Comment by MorvanZhou** [comment]
Hi Haibing,

Please try upgrade you tensorflow as well if you haven't. Please tell me
more details regarding to you case if that doesn't work.

Regards,

Morvan

**Comment by WoNiuHu** [comment]
Thanks, i have update the tensorflow ,  
when i run the command
 in terminal , it has an error , and still haven't the graph 
can you see the picture i attached ?

--

At 2016-11-06 17:20:25, "Morvan" <notifications@github.com> wrote:
Hi,
Please follow these steps again like the first time you install tf.
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html
It will install the latest version.

Regards,

**Comment by MorvanZhou** [comment]
No, I cannot.

**Comment by WoNiuHu** [comment]
hi， Morvan 
    Have you seen the error info ? so what's the matter ? I'm a new learner of tensorflow , how can i familiar with the method of it quickly ,
Can i add your wechat or qq ? 


Thanks & Regards
Haibing








At 2016-11-06 18:45:39, "Morvan" <notifications@github.com> wrote:
No, I cannot.

**Comment by MorvanZhou** [comment]
Hi Haibing,

I still can't find your error info. Sorry.

You can join this QQ group for machine learning: 531670665.
