### ISSUE TITLE
Requests for additions to TensorFlow tutorials

### ISSUE THREAD

**Issue by martiansideofthemoon** [MorvanZhou/tutorials#22]
Hi @MorvanZhou! Really enjoying your tutorials on `tensorflow` :smile: . It would be great if you could add tutorials on the following topics -
*  `variable_scope` / `name_scope` and `tensorflow` scopes in general
*  Data manipulation / Data input functions in `tensorflow`. I'm finding it extremely difficult to find the correct functions to get my data in the correct format.

Thanks!

**Comment by MorvanZhou** [comment]
Hi Kalpesh,

Nice to hear you are interested in those topics. I have added a video for
"scope" but that one is in Chinese.

I don't know when I will do it in English. But you can check the codes for
that video in my github (
https://github.com/MorvanZhou/tutorials/tree/master/tensorflowTUT/tf22_scope
)

For your second request, usually, I do the data manipulation by using
pandas and numpy cause I'm unfamiliar with the tensorflow version.

Best regards,

Morvan

**Comment by martiansideofthemoon** [comment]
@MorvanZhou, would it be possible for you to make `numpy` tutorials in English? Also, could you give me some pointers on implementing a Bidirectional RNN?
