### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by gissemari** [MorvanZhou/tutorials#23]
Hi Morvan!
I would like to know if you have any idea of how to guarantee that the total number of filters we define for a certain layer are not going to measure the same pattern. Does the random initial weights guarantee this?

Gissella

**Comment by MorvanZhou** [comment]
Hi Gissella, 
That's a great question. I guess the random initialization of weights can guarantee they match different features. Some of the filters may look like similar at the end of training, but they should still be different.

Regards

Morvan

**Comment by gissemari** [comment]
Thank you! Cool.
