### ISSUE TITLE
initialize_all_variables is deprecated

### ISSUE THREAD

**Issue by xuyuji9000** [MorvanZhou/tutorials#25]
for the code  of tf14 and tf15 

WARNING:tensorflow:From full_code.py:62 in <module>.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.

**Comment by MorvanZhou** [comment]
Thanks, I've updated all codes
