### ISSUE TITLE
does not appear anything in graph tab in tensorboard

### ISSUE THREAD

**Issue by amirMaleki1** [MorvanZhou/tutorials#26]
@MorvanZhou  i wrote code the tensorboard tutorial section 14 the same as your code , but it is not work for me. in tensorborad does not any things appear in graph tab. i use google chrome on windows. :(  , it does not appear anything in graph tab in tensorboard

**Comment by MorvanZhou** [comment]
Tensorboard on windows may have bugs to be fixed.  Wait for next update.
