### ISSUE TITLE
周神我想问个问题

### ISSUE THREAD

**Issue by JcmeLs** [MorvanZhou/tutorials#29]
用    writer=tf.summary.FileWriter("logs/",sess.graph)生成文件之后用TensorBoard查看，有多个文件我们怎么去区分？或者怎么重命名一个文件，我试过直接重命名不行

**Comment by MorvanZhou** [comment]
多个文件是应为你使用了很多次脚本, 每次都产生了一个文件. 把它们全都删掉, 然后重新 run 一遍,用新产生的看 tensorboard

**Comment by JcmeLs** [comment]
@MorvanZhou 我知道单脚本多次运行时根据时间戳选最新的去渲染，可能 我表达不清楚，不同脚本生成的不同文件，这个我们在tensorboard里面怎么区分，应该是可以命名的，有个demo运行起来是有名字的。。可是我找不到在哪命名.
<img width="312" alt="wx20170116-085700 2x" src="https://cloud.githubusercontent.com/assets/12932339/21967886/c9a20f06-dbc9-11e6-9227-1b8295918cab.png">像上图那样，我们不命名的话就是   .    有命名就是那个eval。可是demo有依赖文件，链接忘了在哪，就不好给你看了。。。

**Comment by JcmeLs** [comment]
@MorvanZhou 找到方法了，并不需要重命名，就是在TensorBoard绑定的目录下的子文件夹就是这里的显示名字
