### ISSUE TITLE
自编码器不能收敛？

### ISSUE THREAD

**Issue by liuguiyangnwpu** [MorvanZhou/tutorials#33]
您好！
我现在使用自编码器学习图像的特征，现在准备使用CIFAR10的数据进行训练，但是却发现在训练一段时间后模型并不你能收敛，导致模型失败？
经过对比，大家使用的数据大多事MNIST的手写识别数据，其数据主要是0／1数据源，而我将CIFAR10的数据归一化到0--1，进行训练，但是依然不能收敛！是不是我的网络有些简单！
我使用的是 （32*32=1024 ---> 521 ---> 256 ---> 512 ---> 1024）这样的模型？请问您做过关于这类的编码器么？

谢谢🙏

**Comment by bigben-plusplus** [comment]
自编码器一般是基于重构误差最小化进行训练的，一般loss函数选用平方误差函数或者交叉熵误差函数。由于解码器输出端一般采用sigmoid激活，其输出范围在[0,1]，所以为了能够获得较小的重构误差，输入数据最好也归一化到[0,1]

训练发散的原因一般是损失函数选择不对或者训练参数设置不合理吧，建议选择交叉熵损失函数和一个较小的学习率训练试试

**Comment by liuguiyangnwpu** [comment]
ok, the problem is fixed, I normalize the input into [-1,1]. 
Thank for your answer.
(PS: My Ubuntu doesn't input chinese .)

**Comment by DerekGrant** [comment]
@liuguiyangnwpu 麻烦问下你除了归一化外还做了其他的处理吗？我把输入除以255再减0.5以后归一化到了-0.5到0.5. 然后再用binary_crossentropy来训练发现loss为负，不知道你有没有遇到这样的问题，谢谢！
