### ISSUE TITLE
save and restore

### ISSUE THREAD

**Issue by alexdongjr** [MorvanZhou/tutorials#35]
Hi Morvan,
您好！您的教程和代码非常好。
关于Reinforcement Learning 部分 像DQN 等training完成之后，尝试save和restore 网络，结果发现与刚training好的效果不一样。估计save和restore 网络的方法有问题，能不能在你的代码上加上saver和restore的部分，非常感谢。

Alex

**Comment by MorvanZhou** [comment]
恩恩, 可能以后有时间会做一做吧
