### ISSUE TITLE
PolicyGradient 里面的动作数目 为啥也是离散化的？

### ISSUE THREAD

**Issue by luochao436** [MorvanZhou/tutorials#39]
hi morvan,
@MorvanZhou 
看完PolicyGradient的教程后，我有个疑惑，说这个方法可以处理连续的动作，比Q - learning处理连续动作更有优势，但是实现的时候最后动作也是离散化的 nb_actions, 这个和Q 网络 输出 的个数也是一致的啊， 怎么体现处理连续 大量的动作的优势呢？？

谢谢！
chao

**Comment by MorvanZhou** [comment]
是可以用于连续动作, 不过 PG 方法比较老, 连续动作需要学很久的时间. 而且现在有新的方法 比如 DDPG,  A3C, 就是专门用在连续动作上的, 所以我在 PG 的时候没讲连续动作的.
