### ISSUE TITLE
CNN那期的google的那个视频的地址？

### ISSUE THREAD

**Issue by lxj0276** [MorvanZhou/tutorials#4]
我记得你讲解cnn时提到的一个google的YouTube的视频，能否告知一下地址，以及视频的名称呢

**Comment by MorvanZhou** [comment]
在这里:
https://classroom.udacity.com/courses/ud730/lessons/6377263405/concepts/64063017560923#

**Comment by lxj0276** [comment]
回复好快，谢谢啦
