### ISSUE TITLE
跑你的CNN程序时出现错误

### ISSUE THREAD

**Issue by tswhnu** [MorvanZhou/tutorials#41]
错误是这样的的：UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd5' in position 87: surrogates not allowed，不知道是哪个地方的错误·

**Comment by MorvanZhou** [comment]
请检查一下你下载的是以什么形式的编码. 或者调整一下你的 IDE 的解码系统, 或者直接再 github 上复制粘贴去你的脚本.
