### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by gknpezgssb** [MorvanZhou/tutorials#47]
tutorials/tensorflowTUT/tensorflow8_feeds.py中把output写成了ouput
<img width="1001" alt="qq20170604-145633 2x" src="https://cloud.githubusercontent.com/assets/9440260/26759651/6bc27300-4936-11e7-9c39-a6439d6ecb14.png">

**Comment by MorvanZhou** [comment]
Thanks and fixed.
