### ISSUE TITLE
How to use a continuous color as the color of a line?

### ISSUE THREAD

**Issue by EmbraceLife** [MorvanZhou/tutorials#49]
Hi Morvan,
Thanks for continuing making great lessons!

I have a question about using matplotlib to create a line with a continuous color, the continuous color should be based on an array. 

The original dataset and question is [here](https://stackoverflow.com/questions/45125877/how-to-fill-the-color-of-a-line-with-a-continuous-color-which-is-created-by-an-a)

Could you teach me how to do it? Thanks

**Comment by MorvanZhou** [comment]
Hi, this is not an issue in the tutorial code. But if you like, you can divide line segment and color them in different colors.
