### ISSUE TITLE
tutorials/tensorflowTUT/tf18_CNN3/full_code.py 进行测试时内存占用过高

### ISSUE THREAD

**Issue by wkcn** [MorvanZhou/tutorials#52]
我在运行tutorials/tensorflowTUT/tf18_CNN3/full_code.py时，
发现测试过程是将整个测试集(10000个测试样例)一次性输入网络中，这样导致测试过程占用的内存达到6G.

我觉得可以这样修改，把test时的batch_size设置为100, 进行多个batch.

但是经过我的测试，输入100个batch_size为100的batch, 运算时间远长于输入一个batch_size = 10000.

这是我的测试代码
```python
import numpy as np
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={xs: batch_xs, ys: batch_ys, keep_prob: 0.5})
    print ("iter: %d" % i)
    if i % 50 == 0:
        w = []
        for _ in range(10):
            batch_txs, batch_tys = mnist.test.next_batch(100)
            a = (compute_accuracy(batch_txs, batch_tys))
            w.append(a)
        print ("Acc: %f" % np.mean(w))
```

**Comment by hcchengithub** [comment]
>  过程占用的内存达到6G.
看哪e得知的?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MorvanZhou** [comment]
我对以前做的 TF 代码进行了提升和更正, 新版的 TF 教学代码在这里, 请查看一下是否还会出现同样的问题? https://github.com/MorvanZhou/Tensorflow-Tutorial. 如果还是存在问题, 请重新 open 这个 issue.

**Comment by wkcn** [comment]
@hcchengithub 
是在System Monitor上查看进程的内存占用得知的，而且我确定是在测试样本时内存占用增加到6G左右。

这个问题是我朋友在学习TF时发现的，我就跑了一下这个代码，发现我也遇到了内存占用过高的情况。

旧版TF的tf18_CNN3把整个测试集(10000个测试样例)一次性输入，相当于batch_size = 10000, 理论各层的输出变量总占用内存为2G.

@MorvanZhou 
新版的TF教学已经没有这个问题了，因为在![401_CNN.py](https://github.com/MorvanZhou/Tensorflow-Tutorial/blob/master/tutorial-contents/401_CNN.py)的第22-23行，已经限定了测试数据为前2000个。
