### ISSUE TITLE
10,000 should be X_test's shape, rather than Y's shape?

### ISSUE THREAD

**Issue by menway** [MorvanZhou/tutorials#62]
https://github.com/MorvanZhou/tutorials/blob/003611340ac29d561e6547e781ddde6973f8f4a8/kerasTUT/5-classifier_example.py#L22

Here 10,000 should be X_test's shape, rather than Y's shape? While 60,000 should be X_train's shape. 

ref: https://github.com/keras-team/keras/blob/master/examples/mnist_mlp.py
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

**Comment by MorvanZhou** [comment]
Thanks, you are right, I will fix this soon.
