### ISSUE TITLE
如何解决 name 'prediction' is not defined

### ISSUE THREAD

**Issue by ChangedenCZD** [MorvanZhou/tutorials#63]
在https://github.com/MorvanZhou/tutorials/tree/master/tensorflowTUT/tf18_CNN2中的代码。
运行时报 name 'prediction' is not defined

**Comment by MorvanZhou** [comment]
请尝试这份代码：
https://github.com/MorvanZhou/Tensorflow-Tutorial/blob/master/tutorial-contents/401_CNN.py

你提到的代码太老了，上面链接是新版代码。

**Comment by ChangedenCZD** [comment]
@MorvanZhou urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by ChangedenCZD** [comment]
新的代码报这个 urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by ChangedenCZD** [comment]
知道原因了，vpn不稳定造成的。

**Comment by ChangedenCZD** [comment]
@MorvanZhou 谢谢您的教程
