### ISSUE TITLE
visualize cpu history

### ISSUE THREAD

**Issue by zhao181** [MorvanZhou/tutorials#68]
![cpuhistory](https://user-images.githubusercontent.com/11849949/40519691-7efec386-5ff3-11e8-9fe3-8be2a03ec2b1.png)

I am using ubuntu16, how can I visualize this cpu history? looking forward to your reply. Thanks a lot

**Comment by MorvanZhou** [comment]
The monitor is what you need in ubuntu

**Comment by zhao181** [comment]
Thanks. I am using ubuntu, but don't know how to show this visualization. Can you tell me which command to use? thanks a lot.

**Comment by MorvanZhou** [comment]
Press home key on your keyboard and type "monitor" and you will find it.
