### ISSUE TITLE
tensorflowTUT/tf12_plot_result/full_code.py NameError: name 'time' is not defined

### ISSUE THREAD

**Issue by Eurus-Holmes** [MorvanZhou/tutorials#70]
when I run `plt.pause(1)`
error:

`Traceback (most recent call last):
  <module>
    plt.pause(1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/pyplot.py", line 294, in pause
    time.sleep(interval)
NameError: name 'time' is not defined`

and...
only scatter shows no lines...

**Comment by MorvanZhou** [comment]
It might be a compatibility problem. Please try updating the matplotlib module.

**Comment by Eurus-Holmes** [comment]
I got it!
when I run in the terminal, it works!
but in the Pycharm, only scatter shows no lines...
