### ISSUE TITLE
Classification那一课

### ISSUE THREAD

**Issue by fzh0917** [MorvanZhou/tutorials#75]
大家有没有遇到输出全是nan的情况呀？原因是因为weights是均值为0、标准差为1的正态分布，有的是绝对值很大的负数，有的是绝对值很大的正数，再被exp取一下幂，导致softmax的分子和分母都炸精度了，导致输出的prediction全是nan。大家是怎么解决这个问题的？

**Comment by MorvanZhou** [comment]
这种时候，建议将learning rate 调低先试试。learning rate 过大会导致更新幅度太大，出现nan
